# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb7e654b67c63979c3d5b46eaf1f749598d0cdb22c5f6ef5291af23f12faad8d21453334f36759e2408625332ccbb713ba6bd56f722d9538a4a961bdc48268b

test:
  secret_key_base: 29c3488bb05e1bc55de463cf8c025f453004994819039e9c7302045d9f707a0df5528dce486aab1e149fa987b8a061761ab4dfaab2753360c8fb201f58505d24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
